version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:

  op-geth:
    image: ghcr.io/bnb-chain/op-geth:${OP_GETH_IMAGE_TAG}
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/op-geth-start.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    ports:
      - ${PORT__OP_GETH:-8547}:8547
      - ${PORT__OP_GETH_WS:-8548}:8548  # Expose WS port
    volumes:
      - ./scripts/:/scripts
      - ./jwt.txt:/jwt.txt
      - op_geth:/geth
    <<: *logging

  op-node:
    image: ghcr.io/bnb-chain/op-node:${OP_NODE_IMAGE_TAG}
    platform: linux/amd64
    depends_on:
      - op-geth
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/op-node-start.sh
    env_file:
      - .env
    ports:
      - ${PORT__OP_NODE_P2P:-9004}:9004
      - ${PORT__OP_NODE:-8551}:8551
    volumes:
      - ./scripts/:/scripts
      - ./jwt.txt:/jwt.txt
      - op_node:/op_node
    <<: *logging

  influxdb-opbnb:
    image: influxdb:latest
    container_name: influxdb-opbnb
    ports:
      - "8089:8089"
    volumes:
      - influxdb-opbnb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=opbnb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=userpassword
    <<: *logging

  grafana-opbnb:
    image: grafana/grafana:latest
    container_name: grafana-opbnb
    depends_on:
      - influxdb-opbnb
    ports:
      - "3000:3000"
    volumes:
      - grafana-opbnb:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    <<: *logging

volumes:
  op_geth:
  op_node:
  influxdb-opbnb:
  grafana-opbnb:
